### ISSUE TITLE
"overflow-y: overlay" is not supported in Firefox

### ISSUE THREAD

**Issue by rururux** [antfu/icones#29]
https://developer.mozilla.org/en-US/docs/Web/CSS/overflow#Values

> overlay
> Only supported in WebKit-based (e.g., Safari) and Blink-based (e.g., Chrome or Opera) browsers. 

i'm using firefox, so i can't scroll down😢

**Comment by antfu** [comment]
Do you know any workaround?

**Comment by rururux** [comment]
It doesn't seem to be possible to do the same in Firefox, so how about use `overflow: auto` instead of `overflow: overlay`, or something like this:
```css
:root {
  --overflow: overlay;
}

@supports not (overflow: overlay) {
  :root {
    --overflow: auto;
  }
}

.overflow-overlay {
  overflow: var(--overflow)
}
```

**Comment by antfu** [comment]
Thanks for the tips. Should be fixed. And the code can actually be simpler.

```css
.overflow-overlay {
  overflow: auto;
  overflow: overlay;
}
```
